import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    color: '#1e40af',
  },
  subtitle: {
    fontSize: 16,
    marginBottom: 12,
    marginTop: 16,
    color: '#1e40af',
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 10,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 8,
    color: '#374151',
  },
  heading1: {
    fontSize: 20,
    marginBottom: 16,
    marginTop: 28,
    color: '#1e3a8a',
    fontWeight: 'bold',
  },
  heading2: {
    fontSize: 14,
    marginBottom: 12,
    marginTop: 20,
    color: '#2563eb',
    fontWeight: 'bold',
  },
  heading3: {
    fontSize: 12,
    marginBottom: 10,
    marginTop: 16,
    color: '#4b5563',
    fontWeight: 'bold',
  },
  listItem: {
    fontSize: 11,
    marginLeft: 12,
    marginBottom: 4,
    color: '#374151',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 9,
    textAlign: 'center',
    color: '#9ca3af',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    marginVertical: 16,
  },
});

// Strip Japanese/CJK characters that Helvetica can't render
const stripCJKCharacters = (text: string): string => {
  // Remove CJK characters (Japanese, Chinese, Korean) and common symbols
  return text.replace(/[\u3000-\u9fff\uac00-\ud7af\uff00-\uffef]/g, '').trim();
};

// Strip markdown formatting for PDF (bold, italic, etc.)
const stripInlineFormatting = (text: string): string => {
  return stripCJKCharacters(
    text
      .replace(/\*\*(.+?)\*\*/g, '$1') // Bold
      .replace(/\*(.+?)\*/g, '$1') // Italic
      .replace(/__(.+?)__/g, '$1') // Bold alt
      .replace(/_(.+?)_/g, '$1') // Italic alt
      .replace(/`(.+?)`/g, '$1') // Code
  );
};

const parseMarkdownToPDF = (content: string) => {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let key = 0;

  lines.forEach(line => {
    const trimmed = line.trim();

    if (trimmed.startsWith('# ')) {
      elements.push(
        <Text key={key++} style={styles.heading1}>
          {stripInlineFormatting(trimmed.replace('# ', ''))}
        </Text>
      );
    } else if (trimmed.startsWith('## ')) {
      elements.push(
        <Text key={key++} style={styles.heading2}>
          {stripInlineFormatting(trimmed.replace('## ', ''))}
        </Text>
      );
    } else if (trimmed.startsWith('### ')) {
      elements.push(
        <Text key={key++} style={styles.heading3}>
          {stripInlineFormatting(trimmed.replace('### ', ''))}
        </Text>
      );
    } else if (trimmed.startsWith('#### ')) {
      elements.push(
        <Text key={key++} style={[styles.heading3, { fontSize: 11 }]}>
          {stripInlineFormatting(trimmed.replace('#### ', ''))}
        </Text>
      );
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      elements.push(
        <Text key={key++} style={styles.listItem}>
          • {stripInlineFormatting(trimmed.replace(/^[-*] /, ''))}
        </Text>
      );
    } else if (/^\d+\.\s/.test(trimmed)) {
      // Numbered list
      const match = trimmed.match(/^(\d+)\.\s(.*)$/);
      if (match) {
        elements.push(
          <Text key={key++} style={styles.listItem}>
            {match[1]}. {stripInlineFormatting(match[2])}
          </Text>
        );
      }
    } else if (trimmed === '---') {
      elements.push(<View key={key++} style={styles.divider} />);
    } else if (trimmed) {
      elements.push(
        <Text key={key++} style={styles.text}>
          {stripInlineFormatting(trimmed)}
        </Text>
      );
    }
  });

  return elements;
};

interface IkigaiPDFDocumentProps {
  content: string;
  date: string;
}

const IkigaiPDFDocument: React.FC<IkigaiPDFDocumentProps> = ({ content, date }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Ikigai Analysis</Text>
      <Text style={[styles.text, { textAlign: 'center', marginBottom: 20 }]}>
        Generated on {date}
      </Text>
      {parseMarkdownToPDF(content)}
      <Text style={styles.footer}>Generated by Ikigai Compass • Find your reason for being</Text>
    </Page>
  </Document>
);

export default IkigaiPDFDocument;
